In [1]:
import pandas as pd
import numpy as np
print(pd.__version__)
print(np.__version__)
import warnings
warnings.filterwarnings('ignore')

0.22.0
1.14.0


In [2]:
data = pd.read_csv('titanic.csv')

In [3]:
data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [7]:
data.describe()

Survived      Pclass         Age       SibSp       ParCh       Fare
count  887.000000  887.000000  887.000000  887.000000  887.000000  887.00000
mean     0.385569    2.305524   29.471443    0.525366    0.383315   32.30542
std      0.487004    0.836662   14.121908    1.104669    0.807466   49.78204
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.00000
25%      0.000000    2.000000   20.250000    0.000000    0.000000    7.92500
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.45420
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.13750
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.32920

In [5]:
# Renaming the columns names for better convinience
data.columns = ['Survived','Pclass','Name','Sex','Age','SibSp', 'ParCh','Fare']
data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  SibSp  ParCh     Fare  
0    male  22.0      1      0   7.2500  
1  female  38.0      1      0  71.2833  
2  female  26.0      0      0   7.9250  
3  female  35.0      1      0  53.1000  
4    male  35.0      0      0   8.0500

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
Survived    887 non-null int64
Pclass      887 non-null int64
Name        887 non-null object
Sex         887 non-null object
Age         887 non-null float64
SibSp       887 non-null int64
ParCh       887 non-null int64
Fare        887 non-null float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.5+ KB


In [8]:
data['Survived'].value_counts()

0    545
1    342
Name: Survived, dtype: int64

In [9]:
data['Pclass'].value_counts()

3    487
1    216
2    184
Name: Pclass, dtype: int64

In [12]:
for idx, passengers_count in enumerate(data['Pclass'].value_counts().sort_index()):
    print('passengers survived in class_%d: %d\nsurvival rate: %d percent'%(idx+1, data[(data.Pclass == (idx+1)) & (data.Survived == 1)]['Survived'].count(),
         float(int(data[(data.Pclass == (idx+1)) & (data.Survived == 1)]['Survived'].count())/(passengers_count)*100)))

passengers survived in class_1: 136
survival rate: 62 percent
passengers survived in class_2: 87
survival rate: 47 percent
passengers survived in class_3: 119
survival rate: 24 percent


In [13]:
data['Sex'].value_counts()

male      573
female    314
Name: Sex, dtype: int64

In [14]:
print('female passengers who survived are: %d'%data[(data.Sex == 'female') & (data.Survived == 1)]['Survived'].count())
print('male passengers who survived are: %d'%data[(data.Sex == 'male') & (data.Survived == 1)]['Survived'].count())


female passengers who survived are: 233
male passengers who survived are: 109


In [15]:
print('survival rate of female passangers: %d percent'%((233/314)*100))
print('survival rate of male passangers: %d percent'%((109/573)* 100))

survival rate of female passangers: 74 percent
survival rate of male passangers: 19 percent


In [16]:
data['Sex'].value_counts()

male      573
female    314
Name: Sex, dtype: int64

In [19]:
data['SibSp'].value_counts().sort_index()

0    604
1    209
2     28
3     16
4     18
5      5
8      7
Name: SibSp, dtype: int64

In [20]:
data['ParCh'].value_counts().sort_index()

0    674
1    118
2     80
3      5
4      4
5      5
6      1
Name: ParCh, dtype: int64

In [24]:
for idx, passenger_count in enumerate(data['SibSp'].value_counts().sort_index()):
    print('passengers with %d siblings/spouse who survived are: %d\nsurvival rate: %d percent'%(idx, data[(data['SibSp'] == (idx)) & (data.Survived == 1)]['Survived'].count(),
         float(int(data[(data['SibSp'] == (idx)) & (data.Survived == 1)]['Survived'].count())/(passenger_count)*100)))

passengers with 0 siblings/spouse who survived are: 210
survival rate: 34 percent
passengers with 1 siblings/spouse who survived are: 112
survival rate: 53 percent
passengers with 2 siblings/spouse who survived are: 13
survival rate: 46 percent
passengers with 3 siblings/spouse who survived are: 4
survival rate: 25 percent
passengers with 4 siblings/spouse who survived are: 3
survival rate: 16 percent
passengers with 5 siblings/spouse who survived are: 0
survival rate: 0 percent
passengers with 6 siblings/spouse who survived are: 0
survival rate: 0 percent


In [25]:
for idx, passenger_count in enumerate(data['ParCh'].value_counts().sort_index()):
    print('passengers with %d parents/childrens who survived are: %d\nsurvival rate: %d percent'%(idx, data[(data['ParCh'] == (idx)) & (data.Survived == 1)]['Survived'].count(),
         float(int(data[(data['ParCh'] == (idx)) & (data.Survived == 1)]['Survived'].count())/(passenger_count)*100)))

passengers with 0 parents/childrens who survived are: 233
survival rate: 34 percent
passengers with 1 parents/childrens who survived are: 65
survival rate: 55 percent
passengers with 2 parents/childrens who survived are: 40
survival rate: 50 percent
passengers with 3 parents/childrens who survived are: 3
survival rate: 60 percent
passengers with 4 parents/childrens who survived are: 0
survival rate: 0 percent
passengers with 5 parents/childrens who survived are: 1
survival rate: 20 percent
passengers with 6 parents/childrens who survived are: 0
survival rate: 0 percent


In [26]:
# Since the feature Name is not really helpful for our classfication model, its better to 
# drop it from our dataset
data = data.drop('Name', axis = 1)
data.head()

Survived  Pclass     Sex   Age  SibSp  ParCh     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [27]:
# Test_train split using StratifiedShuffleSplit
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(data, data["Survived"]):
    train = data.loc[train_index]
    test = data.loc[test_index]

In [28]:
train.shape

(709, 7)

In [29]:
test.shape

(178, 7)

In [30]:
# seperating the features and target variables for our data
X_train = train.drop('Survived', axis = 1)
y_train = train['Survived'].copy()

In [31]:
# Keeping aside the features and target variables for our data
X_test = test.drop('Survived', axis = 1)
y_test = test['Survived'].copy()

In [46]:
# Building a custom class that can help us seperate the numeric and catrgorical features

from sklearn.base import BaseEstimator, TransformerMixin

class FeatureSelector(BaseEstimator,TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y= None):
        return self
    def transform(self, X):
        return X[self.attribute_names]



In [37]:
# Seperating the numeric and categorical values using our above built custom Class

from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import Imputer

# building a pipeline for the numeric variables
num_pipeline = Pipeline([
    ('numeric_features', FeatureSelector(["Age","Fare", "SibSp","ParCh"]))
])

num_pipeline.fit_transform(X_train)[:10]

Age     Fare  SibSp  ParCh
851  18.0   9.3500      0      1
650  16.0   7.8292      0      0
103  37.0   7.9250      2      0
101  21.0  77.2875      0      1
292  24.0   7.8958      0      0
233  24.0  10.5000      0      0
763  30.5   7.7500      0      0
873  19.0   7.8958      0      0
249  18.0   7.2500      0      0
513  34.0  10.5000      0      0

In [80]:
# coverting the textual object features into categorical features
X_train['Sex']= X_train['Sex'].astype('category')
X_train['Sex'] = X_train['Sex'].cat.codes

In [81]:
X_train.head()

Pclass  Sex   Age  SibSp  ParCh     Fare
851       3    0  18.0      0      1   9.3500
650       3    0  16.0      0      0   7.8292
103       3    1  37.0      2      0   7.9250
101       1    1  21.0      0      1  77.2875
292       3    1  24.0      0      0   7.8958

In [84]:
# using random forest classifier for the above problem
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, cross_val_predict

forest_clf = RandomForestClassifier(random_state = 42)
forest_scores = cross_val_score(forest_clf, X_train, y_train, cv= 10)
forest_scores.mean()

0.8167583277442432

In [86]:
forest_predict = cross_val_predict(forest_clf, X_train, y_train, cv= 10)

In [87]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, forest_predict)

array([[382,  54],
       [ 76, 197]])

In [92]:
from sklearn.svm import SVC
svm_clf = SVC()
svm_score = cross_val_score(svm_clf, X_train, y_train, cv= 10)
svm_predict = cross_val_predict(svm_clf, X_train, y_train, cv= 10)
svm_score.mean()

0.705118488710038

In [93]:
confusion_matrix(y_train, svm_predict)

array([[367,  69],
       [140, 133]])

In [94]:
from sklearn.linear_model import SGDClassifier
SGD_clf = SGDClassifier(max_iter=5, random_state=42)
SGD_score = cross_val_score(SGD_clf, X_train, y_train, cv= 10).mean()
SGD_predict = cross_val_predict(SGD_clf, X_train, y_train, cv= 10)
SGD_score

0.5148781578359044

In [95]:
confusion_matrix(y_train, SGD_predict)

array([[159, 277],
       [ 68, 205]])

In [105]:
# one-hot-encoding the Pclass column
X_transform = pd.get_dummies(X_train, columns=["Pclass",'Sex','SibSp','ParCh'])
X_transform.shape

(709, 21)

In [106]:
svm_score = cross_val_score(svm_clf, X_transform, y_train, cv= 10)
svm_predict = cross_val_predict(svm_clf, X_transform, y_train, cv= 10)
svm_score.mean()

0.7334697071316789

In [107]:
confusion_matrix(y_train, svm_predict)

array([[360,  76],
       [113, 160]])

In [108]:
forest_clf = RandomForestClassifier(random_state = 42)
forest_scores = cross_val_score(forest_clf, X_transform, y_train, cv= 10)
forest_scores.mean()

0.7997361949474625

In [109]:
SGD_score = cross_val_score(SGD_clf, X_transform, y_train, cv= 10).mean()
SGD_predict = cross_val_predict(SGD_clf, X_transform, y_train, cv= 10)
SGD_score

0.5273977196512408

In [111]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_jobs=-1, weights='distance', n_neighbors=4)
knn_scores = cross_val_score(knn_clf, X_transform, y_train, cv= 10)
knn_scores.mean()

0.706485580147552